# Generated by Django 3.0.8 on 2020-07-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='c_current',
            field=models.IntegerField(default=0),
        ),
    ]
